CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254)             NOT NULL,
    password_hash VARCHAR(255)             NOT NULL,
    full_name     VARCHAR(100)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE incomes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    source      VARCHAR(120)             NOT NULL,
    amount      NUMERIC(14, 2)           NOT NULL CHECK (amount > 0),
    received_on DATE                     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_incomes_user_date ON incomes (user_id, received_on);

CREATE TABLE expenses (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    description VARCHAR(120)             NOT NULL,
    category    VARCHAR(20)              NOT NULL
        CHECK (category IN ('FOOD', 'TRANSPORT', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'OTHER')),
    amount      NUMERIC(14, 2)           NOT NULL CHECK (amount > 0),
    spent_on    DATE                     NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_expenses_user_date ON expenses (user_id, spent_on);

CREATE TABLE budgets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category      VARCHAR(20)    NOT NULL
        CHECK (category IN ('FOOD', 'TRANSPORT', 'EDUCATION', 'ENTERTAINMENT', 'HEALTH', 'OTHER')),
    monthly_limit NUMERIC(14, 2) NOT NULL CHECK (monthly_limit > 0),
    CONSTRAINT uk_budgets_user_category UNIQUE (user_id, category)
);

CREATE TABLE saving_goals (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT                   NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name           VARCHAR(100)             NOT NULL,
    target_amount  NUMERIC(14, 2)           NOT NULL CHECK (target_amount > 0),
    saved_amount   NUMERIC(14, 2)           NOT NULL DEFAULT 0 CHECK (saved_amount >= 0),
    monthly_saving NUMERIC(14, 2)           NOT NULL DEFAULT 0 CHECK (monthly_saving >= 0),
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_saving_goals_user ON saving_goals (user_id);
